var GAME_LEVELS = [
   ["x                                                                                               x ",
   " x                                                                                               x ",
   " x                                                                                               x ",
   " x                                             c                                                 x ",
   " x                    c                                                                          x ",
   " x                                           xxxx                                                x ",
   " x                  xxxxx                                                      xxx               x ",
   " x                          xxxx                                                                 x ",
   " x                                  xxxxxx                                                       x ",
   " x                                                          xxxxx                                x ",
   " x                                                                    xxxx                       x ",
   " x                                                xxxxxxx                                        x ",
   " x                                         xxxx                                                  x ",
   " x                                                                                               x ",
   " x                                xxxxx                                                   p      x ",
   " x                   xxxxxxx                                                    c        xxx     x ",
   " x    @                                                                                          x ",
   " x xxxxxxxxxxxxx                                                              xxxx               x ",
   " x                                                                                               x ",
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                   "],
  ["          x        x                                                                                               ",
   "          x        x                                                                                               ",
   "          x        x                                                                                               ",
   "          x        x                                                                                               ",
   "          x        x    c                                                                                          ",
   "          x        x                                                              c                                ",
   "          x        x    x                                                                                          ",
   "          x        x         xx                                         xxx     xxxx     xxxxxxxxx                 ",
   "          x        x               xxxx                                                  x                         ",
   "          x        x                        xxx                                          x                         ",
   "          x        x                                xxxx       xxxx                      x           xxxxx         ",
   "          x        x                                   x                                 x                         ",
   "          x        x                                   x                        xxx      x                         ",
   "          x        x                                   x                                 x             e           ",
   "          x        x                                   x                xxxx             x                         ",
   "          x        x                                   x                e                x        xx               ",
   "          x        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                 x                         ",
   "          x        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       xxxx                      x                c        ",
   "          x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 x                         ",
   "          x                                                                              x             e           ",
   "          x                                                              xxxx            x                         ",
   "          x                                                                              x                         ",
   "          x                                                  xxxxxx                      x               p         ",
   "          x                       c     c                                                x               p         ",
   "          x    @     xxxxx                       xxxxxxx                                 x             xxxxx       ",
   "          x   xx               xxxxxxxxxxxx                                              x                         ",
   "          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                            xxxxxxxxxxxx                                                                x  ",
   "  x                            x!!!!!!!!!!x                                  c                             x  ",
   "  x                            xxxxxxxxxx!x                                          xx    x               x  ",
   "  x                                     x!x                                 xxxxx          x               x  ",
   "  x                                     x!x                                                x               x  ",
   "  x                                     x!x                                                x               x  ",
   "  x                                     xvx                         xxxxx                  x               x  ",
   "  x                                                                                        x               x  ",
   "  x                                                                          xxxx          x       c       x  ",
   "  x                                                                                        x               x  ",
   "  x                                                      c         xxxxx                   x               x  ",
   "  x                                                            xx                          x               x  ",
   "  x                                                     xxx                                x               x  ",
   "  x c                                                x                                     x               x  ",
   "  x                   xxxx       xxxxxx       xxxx                                         x               x  ",
   "  x              xx                                                                        x               x  ",
   "  x               xssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssx               x  ",
   "  xxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               x  ",
   "  x                                                                                              c         x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  xxxx                                                                                                     x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  xxxx                                                                                                     x  ",
   "  x      xxx                  c             xxxxx                                                          x  ",
   "  x            xxxx                   xx                               c                                   x  ",
   "  x                   xx    xxxxxx                    xxx                                                  x  ",
   "  x                                                                    xx   xxxxx                          x  ",
   "  x                                                             xxxx                                       x  ",
   "  x                                                                                   xxxxxx               x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    @      p   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  [" x                               c                                                                       x ",
   " x       x                                                                                               x ",
   " x       x   c        xxxxxxxxxxxxxxxxxxx                                                                x ",
   " x       x            x f  f  f  f  f   x    xxxxxx                                                      x ",
   " x       x xxxxx      x                 x                                                                x ",
   " x       x   f        x                 x               xxxxx                                            x ",
   " x       x         xxxx                 x                                         c                      x ",
   " x       x            x                 x   c                                                            x ",
   " x       x   xxxx     x                 x                                       xxxxx                    x ",
   " x       x            x                 x   xx    x    xxx     x    xxxxx   x                            x ",
   " x       x          xxx                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  x ",
   " x       x            x                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  x ",
   " x       x            x                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  x ",
   " x       x  xxxx      x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  x ",
   " x       x   f    c   x                                                                    xxxx          x ",
   " x       x            x                       c                                                          x ",
   " x       x       xxx  x               x                                                                  x ",
   " x       x            x               x                                                                  x ",
   " x       x            x               xxxx    xxxxx      xxxx                                            x ",
   " x       xxx          x               x                                                           xxx    x ",
   " x       x f          x           xxx x                                                                  x ",
   " x       x        xx  x               x         xxxxx                                                    x ",
   " x       x            x       xx      x                                                                  x ",
   " x       x            x               x                    xxxxx       c                                 x ",
   " x       x     xx     x               x                                                                  x ",
   " x       x            x xxx           x                              xxxxxx                              x ",
   " x       x            x               x                                                                  x ",
   " xxxxxxxxx         xxxx               x                                                                  x ",
   " x                    x               x        c           xxxxx                                         x ",
   " x                    x            c  x                                 e                          c     x ",
   " x    @               x     p         x               xx                        e                        x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                           "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
